### ISSUE TITLE
UDF outputSchema doesn't match exec return type

### ISSUE THREAD

**Issue by tristanreid** [nielsbasjes/tdigest-pig#1]
Wonderful library - thank you!

The UDF's return type is Tuple (https://github.com/nielsbasjes/tdigest-pig/blob/master/src/main/java/nl/basjes/pig/stats/tdigest/Quantile.java#L14), but the outputSchema shows a type of Double (https://github.com/nielsbasjes/tdigest-pig/blob/master/src/main/java/nl/basjes/pig/stats/tdigest/Quantile.java#L90)

The impact of this is that a DESCRIBE on the result will show a type of double, but the data is in fact a tuple.  Storing this into a typed data store (e.g. parquet) will fail, and since pig believes the type is double it won't allow deferencing the tuple.

I'd be happy to do a PR to fix this if you'd like?  On my local copy I've changed the type to Double which fixes the issue, but if you'd like for me to instead change the outputSchema I'd be happy to go that route instead.

Thanks,

T

**Comment by nielsbasjes** [comment]
Hi. 
Thanks for reporting this problem.
I simply changed the output of the Quantile UDF to Double and updated all the relevant tests and such.

I pushed these changes to github just now and I would really appreciate it if you can validate my changes.

Niels

**Comment by tristanreid** [comment]
It works perfectly - thanks!
